kind: Service
apiVersion: v1
metadata:
  name: gke-3-app
spec:
  selector:
    app: gke-3-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gke-3-app
  labels:
    app: gke-3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-3-app
  template:
    metadata:
      labels:
        app: gke-3-app
    spec:
      containers:
      - name: gke-3-app
        image: gcr.io/jendevops1/gke-3-app:d7614232afa55ce172eb9b2a16a57aeb4b6f850c
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
